<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Net.Codecrete.QrCodeGenerator" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HarmonyPcTouchpad.Agent.Core\HarmonyPcTouchpad.Agent.Core.csproj" />
    <ProjectReference Include="..\HarmonyPcTouchpad.Agent.Security\HarmonyPcTouchpad.Agent.Security.csproj" />
    <ProjectReference Include="..\HarmonyPcTouchpad.Agent.Transport\HarmonyPcTouchpad.Agent.Transport.csproj" />
    <ProjectReference Include="..\HarmonyPcTouchpad.Agent.Windows\HarmonyPcTouchpad.Agent.Windows.csproj" />
  </ItemGroup>
</Project>
